#!/bin/sh
set -e

mkdir -p target/classes target/test-classes

javac -d target/classes src/main/java/com/baldurtech/miniature/spice/*.java
javac -d target/test-classes -classpath lib/reflections-0.9.9-RC2.jar:target/classes src/test/java/com/baldurtech/miniature/spice/*.java
