#!/bin/sh
set -e

mkdir -p target/classes target/test-classes

javac -d target/classes src/main/java/com/baldurtech/miniature/spice/*.java
javac -d target/test-classes -classpath target/classes src/test/java/com/baldurtech/miniature/spice/*.java
